### PR TITLE
Added Russian translations (+more)

### PR DESCRIPTION
**Pull request by rodionmoiseev**
Also made all language names appear only in their own language for discoverability.

### CODE REVIEW

**Comment by rodionmoiseev** [comment]
Here we are. I have made some changes to `Languages.java` the way I think is appropriate (using the Wikipedia's "Read in other language" section as a reference).

**Comment by kevinrobayna** [comment]
yes, it's more logic that each one see in language the language that he understand. Thanks, we really appreciate what you just did.

**Comment by skatrak** [comment]
@rodionmoiseev thank you very much. We appreciate your help.
Actually I was going to make that same modification right now, before I saw your pull request.

**Comment by rodionmoiseev** [comment]
Glad to help. Always welcome any suggestions on improving c10n that you may discover. Cheers!

**Pull request merged**
